### ISSUE TITLE
No Mention in Introduction of CUT&Tag Data Type

### ISSUE THREAD

**Issue by DarioS** [LTLA/csawBook#2]
Could the introduction to the book have a couple of sentences regarding csaw's applicability to CUT&Tag / CUT&RUN data? Also Section 2.1 of the book has numerous instances of (???) which suggests broken cross-references.

**Comment by LTLA** [comment]
Remember usng **csaw** for CUT&RUN a few times, but don't really remember much about it, so not sure I can say all that much. I think it worked out okay but I'm not sure. PR welcome.

Anyway, the broken references should be fixed in 92184bc34b1c78160bbac8cf9abbe332d5e03300. lmk if you see any more.
